"""create_connections_table

Revision ID: 034ffbe4f275
Revises: 76c8d5e89e05
Create Date: 2025-10-07 11:30:20.941925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034ffbe4f275'
down_revision = '76c8d5e89e05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
