"""Replace pronouns field with dream_role

Revision ID: 073b492c6fea
Revises: a9cedb67f821
Create Date: 2025-10-07 04:24:47.230992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073b492c6fea'
down_revision = 'a9cedb67f821'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dream_role', sa.String(), nullable=True))
    op.drop_column('users', 'pronouns')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pronouns', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'dream_role')
    # ### end Alembic commands ###
