"""add_gender_and_religion_fields_to_users

Revision ID: 76c8d5e89e05
Revises: 073b492c6fea
Create Date: 2025-10-07 05:12:16.653551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c8d5e89e05'
down_revision = '073b492c6fea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('users', sa.Column('religion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'religion')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
