"""Add university profile fields to users table

Revision ID: a9cedb67f821
Revises: f806dad06d1b
Create Date: 2025-10-07 04:15:27.960756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9cedb67f821'
down_revision = 'f806dad06d1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('school_email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_school_email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('university', sa.String(), nullable=True))
    op.add_column('users', sa.Column('campus', sa.String(), nullable=True))
    op.add_column('users', sa.Column('enrollment_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('major', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_class', sa.String(), nullable=True))
    op.add_column('users', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('current_role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('current_organization', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('one_line_bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('full_bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('hobbies', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('pronouns', sa.String(), nullable=True))
    op.add_column('users', sa.Column('links', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'links')
    op.drop_column('users', 'pronouns')
    op.drop_column('users', 'interests')
    op.drop_column('users', 'hobbies')
    op.drop_column('users', 'full_bio')
    op.drop_column('users', 'one_line_bio')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'current_organization')
    op.drop_column('users', 'current_role')
    op.drop_column('users', 'graduation_year')
    op.drop_column('users', 'current_class')
    op.drop_column('users', 'major')
    op.drop_column('users', 'enrollment_status')
    op.drop_column('users', 'campus')
    op.drop_column('users', 'university')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'is_school_email_verified')
    op.drop_column('users', 'school_email')
    # ### end Alembic commands ###
